import { Exercise } from './types';
import { FitnessIcon, BodyIcon, WalkIcon, BarbellIcon, AccessibilityIcon, HeartIcon } from '../icons';

// Comprehensive muscle group categories with proper mapping
export const MUSCLE_GROUPS = [
  { id: 'chest', name: 'Chest', icon: 'fitness-outline', color: '#FF6B6B', IconComponent: FitnessIcon },
  { id: 'back', name: 'Back', icon: 'body-outline', color: '#4ECDC4', IconComponent: BodyIcon },
  { id: 'legs', name: 'Legs', icon: 'walk-outline', color: '#45B7D1', IconComponent: WalkIcon },
  { id: 'biceps', name: 'Biceps', icon: 'barbell-outline', color: '#96CEB4', IconComponent: BarbellIcon },
  { id: 'triceps', name: 'Triceps', icon: 'barbell-outline', color: '#FFEAA7', IconComponent: BarbellIcon },
  { id: 'shoulders', name: 'Shoulders', icon: 'accessibility-outline', color: '#DDA0DD', IconComponent: AccessibilityIcon },
  { id: 'core', name: 'Core/Abs', icon: 'body-outline', color: '#98D8C8', IconComponent: BodyIcon },
  { id: 'cardio', name: 'Cardio', icon: 'heart-outline', color: '#F7DC6F', IconComponent: HeartIcon },
];

// Muscle mapping for proper categorization
const muscleMapping: { [key: string]: string } = {
  // Chest muscles
  'chest': 'chest',
  'pectorals': 'chest',
  'pecs': 'chest',
  
  // Back muscles
  'lats': 'back',
  'latissimus dorsi': 'back',
  'middle back': 'back',
  'lower back': 'back',
  'upper back': 'back',
  'rhomboids': 'back',
  'rear delts': 'back',
  'traps': 'back',
  'trapezius': 'back',
  
  // Leg muscles
  'quadriceps': 'legs',
  'quads': 'legs',
  'hamstrings': 'legs',
  'glutes': 'legs',
  'calves': 'legs',
  'thighs': 'legs',
  'legs': 'legs',
  
  // Arm muscles
  'biceps': 'biceps',
  'triceps': 'triceps',
  'forearms': 'biceps',
  
  // Shoulder muscles
  'shoulders': 'shoulders',
  'delts': 'shoulders',
  'deltoids': 'shoulders',
  'front delts': 'shoulders',
  'side delts': 'shoulders',
  
  // Core muscles
  'abs': 'core',
  'abdominals': 'core',
  'core': 'core',
  'obliques': 'core',
  'waist': 'core',
  
  // Cardio
  'cardio': 'cardio',
  'cardiovascular': 'cardio',
};
// Exercise images mapping - React Native requires static imports
const exerciseImages: { [key: string]: any } = {
  // CHEST EXERCISES
  'pushups': require('../../free-exercise-db-main/exercises/Pushups/0.jpg'),
  'incline_push_up': require('../../free-exercise-db-main/exercises/Incline_Push-Up/0.jpg'),
  'decline_push_up': require('../../free-exercise-db-main/exercises/Decline_Push-Up/0.jpg'),
  'dumbbell_bench_press': require('../../free-exercise-db-main/exercises/Dumbbell_Bench_Press/0.jpg'),
  'dumbbell_flyes': require('../../free-exercise-db-main/exercises/Dumbbell_Flyes/0.jpg'),
  'barbell_bench_press': require('../../free-exercise-db-main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg'),
  'incline_dumbbell_press': require('../../free-exercise-db-main/exercises/Incline_Dumbbell_Press/0.jpg'),
  'incline_dumbbell_flyes': require('../../free-exercise-db-main/exercises/Incline_Dumbbell_Flyes/0.jpg'),
  'decline_dumbbell_press': require('../../free-exercise-db-main/exercises/Decline_Dumbbell_Bench_Press/0.jpg'),
  'cable_crossover': require('../../free-exercise-db-main/exercises/Cable_Crossover/0.jpg'),
  'dips_chest': require('../../free-exercise-db-main/exercises/Dips_-_Chest_Version/0.jpg'),
  'wide_grip_bench_press': require('../../free-exercise-db-main/exercises/Wide-Grip_Barbell_Bench_Press/0.jpg'),
  
  // BACK EXERCISES
  'pullups': require('../../free-exercise-db-main/exercises/Pullups/0.jpg'),
  'chin_up': require('../../free-exercise-db-main/exercises/Chin-Up/0.jpg'),
  'bent_over_barbell_row': require('../../free-exercise-db-main/exercises/Bent_Over_Barbell_Row/0.jpg'),
  'one_arm_dumbbell_row': require('../../free-exercise-db-main/exercises/One-Arm_Dumbbell_Row/0.jpg'),
  'wide_grip_lat_pulldown': require('../../free-exercise-db-main/exercises/Wide-Grip_Lat_Pulldown/0.jpg'),
  'seated_cable_rows': require('../../free-exercise-db-main/exercises/Seated_Cable_Rows/0.jpg'),
  't_bar_row': require('../../free-exercise-db-main/exercises/T-Bar_Row_with_Handle/0.jpg'),
  'reverse_flyes': require('../../free-exercise-db-main/exercises/Reverse_Flyes/0.jpg'),
  'face_pull': require('../../free-exercise-db-main/exercises/Face_Pull/0.jpg'),
  'hyperextensions': require('../../free-exercise-db-main/exercises/Hyperextensions_Back_Extensions/0.jpg'),
  
  // LEG EXERCISES
  'barbell_squat': require('../../free-exercise-db-main/exercises/Barbell_Squat/0.jpg'),
  'bodyweight_squat': require('../../free-exercise-db-main/exercises/Bodyweight_Squat/0.jpg'),
  'dumbbell_lunges': require('../../free-exercise-db-main/exercises/Dumbbell_Lunges/0.jpg'),
  'barbell_deadlift': require('../../free-exercise-db-main/exercises/Barbell_Deadlift/0.jpg'),
  'leg_press': require('../../free-exercise-db-main/exercises/Leg_Press/0.jpg'),
  'leg_extensions': require('../../free-exercise-db-main/exercises/Leg_Extensions/0.jpg'),
  'lying_leg_curls': require('../../free-exercise-db-main/exercises/Lying_Leg_Curls/0.jpg'),
  'standing_calf_raises': require('../../free-exercise-db-main/exercises/Standing_Calf_Raises/0.jpg'),
  'hack_squat': require('../../free-exercise-db-main/exercises/Hack_Squat/0.jpg'),
  'romanian_deadlift': require('../../free-exercise-db-main/exercises/Romanian_Deadlift/0.jpg'),
  'front_squat': require('../../free-exercise-db-main/exercises/Front_Barbell_Squat/0.jpg'),
  'walking_lunges': require('../../free-exercise-db-main/exercises/Barbell_Walking_Lunge/0.jpg'),
  'sumo_deadlift': require('../../free-exercise-db-main/exercises/Sumo_Deadlift/0.jpg'),
  'goblet_squat': require('../../free-exercise-db-main/exercises/Goblet_Squat/0.jpg'),
  
  // BICEP EXERCISES
  'dumbbell_bicep_curl': require('../../free-exercise-db-main/exercises/Dumbbell_Bicep_Curl/0.jpg'),
  'barbell_curl': require('../../free-exercise-db-main/exercises/Barbell_Curl/0.jpg'),
  'hammer_curls': require('../../free-exercise-db-main/exercises/Hammer_Curls/0.jpg'),
  'concentration_curls': require('../../free-exercise-db-main/exercises/Concentration_Curls/0.jpg'),
  'preacher_curl': require('../../free-exercise-db-main/exercises/Preacher_Curl/0.jpg'),
  'ez_bar_curl': require('../../free-exercise-db-main/exercises/EZ-Bar_Curl/0.jpg'),
  'cable_bicep_curl': require('../../free-exercise-db-main/exercises/Standing_Biceps_Cable_Curl/0.jpg'),
  'incline_dumbbell_curl': require('../../free-exercise-db-main/exercises/Incline_Dumbbell_Curl/0.jpg'),
  'alternate_hammer_curl': require('../../free-exercise-db-main/exercises/Alternate_Hammer_Curl/0.jpg'),
  
  // TRICEP EXERCISES
  'triceps_pushdown': require('../../free-exercise-db-main/exercises/Triceps_Pushdown/0.jpg'),
  'dips_triceps_version': require('../../free-exercise-db-main/exercises/Dips_-_Triceps_Version/0.jpg'),
  'tricep_dumbbell_kickback': require('../../free-exercise-db-main/exercises/Tricep_Dumbbell_Kickback/0.jpg'),
  'bench_dips': require('../../free-exercise-db-main/exercises/Bench_Dips/0.jpg'),
  'ez_bar_skullcrusher': require('../../free-exercise-db-main/exercises/EZ-Bar_Skullcrusher/0.jpg'),
  'overhead_tricep_extension': require('../../free-exercise-db-main/exercises/Standing_Dumbbell_Triceps_Extension/0.jpg'),
  'close_grip_bench_press': require('../../free-exercise-db-main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg'),
  'tricep_rope_pushdown': require('../../free-exercise-db-main/exercises/Triceps_Pushdown_-_Rope_Attachment/0.jpg'),
  
  // SHOULDER EXERCISES
  'dumbbell_shoulder_press': require('../../free-exercise-db-main/exercises/Dumbbell_Shoulder_Press/0.jpg'),
  'side_lateral_raise': require('../../free-exercise-db-main/exercises/Side_Lateral_Raise/0.jpg'),
  'front_dumbbell_raise': require('../../free-exercise-db-main/exercises/Front_Dumbbell_Raise/0.jpg'),
  'barbell_shoulder_press': require('../../free-exercise-db-main/exercises/Barbell_Shoulder_Press/0.jpg'),
  'arnold_dumbbell_press': require('../../free-exercise-db-main/exercises/Arnold_Dumbbell_Press/0.jpg'),
  'upright_row': require('../../free-exercise-db-main/exercises/Upright_Barbell_Row/0.jpg'),
  'rear_delt_fly': require('../../free-exercise-db-main/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/0.jpg'),
  'military_press': require('../../free-exercise-db-main/exercises/Standing_Military_Press/0.jpg'),
  
  // CORE EXERCISES
  'crunches': require('../../free-exercise-db-main/exercises/Crunches/0.jpg'),
  'plank': require('../../free-exercise-db-main/exercises/Plank/0.jpg'),
  'russian_twist': require('../../free-exercise-db-main/exercises/Russian_Twist/0.jpg'),
  'hanging_leg_raise': require('../../free-exercise-db-main/exercises/Hanging_Leg_Raise/0.jpg'),
  'sit_up': require('../../free-exercise-db-main/exercises/Sit-Up/0.jpg'),
  'bicycle_crunches': require('../../free-exercise-db-main/exercises/Air_Bike/0.jpg'),
  'dead_bug': require('../../free-exercise-db-main/exercises/Dead_Bug/0.jpg'),
  'ab_wheel_rollout': require('../../free-exercise-db-main/exercises/Ab_Roller/0.jpg'),
  'leg_raises': require('../../free-exercise-db-main/exercises/Leg_Lift/0.jpg'),
  'oblique_crunches': require('../../free-exercise-db-main/exercises/Oblique_Crunches/0.jpg'),
  
  // CARDIO EXERCISES
  'mountain_climbers': require('../../free-exercise-db-main/exercises/Mountain_Climbers/0.jpg'),
  'rope_jumping': require('../../free-exercise-db-main/exercises/Rope_Jumping/0.jpg'),
  'running_treadmill': require('../../free-exercise-db-main/exercises/Running_Treadmill/0.jpg'),
  'burpees': require('../../free-exercise-db-main/exercises/Pushups/0.jpg'), // Using pushups as fallback
  'jumping_jacks': require('../../free-exercise-db-main/exercises/Star_Jump/0.jpg'),
  'high_knees': require('../../free-exercise-db-main/exercises/Knee_Tuck_Jump/0.jpg'),
  'box_jumps': require('../../free-exercise-db-main/exercises/Box_Jump_Multiple_Response/0.jpg'),
};
// All exercises from your database - organized by categories with proper images
const ALL_EXERCISES: Exercise[] = [
  // CHEST EXERCISES
  {
    id: 'pushups',
    name: 'Pushups',
    type: 'strength',
    muscle: 'chest',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['pushups']],
    gifUrl: exerciseImages['pushups'],
  },
  {
    id: 'incline_push_up',
    name: 'Incline Push-Up',
    type: 'strength',
    muscle: 'chest',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Place your hands on an elevated surface and perform push-ups. This variation is easier than regular push-ups.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['incline_push_up']],
    gifUrl: exerciseImages['incline_push_up'],
  },
  {
    id: 'decline_push_up',
    name: 'Decline Push-Up',
    type: 'strength',
    muscle: 'chest',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Place your feet on an elevated surface and perform push-ups. This variation is harder than regular push-ups.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['decline_push_up']],
    gifUrl: exerciseImages['decline_push_up'],
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    type: 'strength',
    muscle: 'chest',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Lie on a bench with dumbbells in each hand. Press the weights up and together, then lower them back down.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['dumbbell_bench_press']],
    gifUrl: exerciseImages['dumbbell_bench_press'],
  },
  {
    id: 'dumbbell_flyes',
    name: 'Dumbbell Flyes',
    type: 'strength',
    muscle: 'chest',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Lie on a bench with dumbbells. Lower the weights in an arc motion, then bring them back together.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders'],
    images: [exerciseImages['dumbbell_flyes']],
    gifUrl: exerciseImages['dumbbell_flyes'],
  },
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    type: 'strength',
    muscle: 'chest',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Lie on a bench and press the barbell up from your chest, then lower it back down.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['barbell_bench_press']],
    gifUrl: exerciseImages['barbell_bench_press'],
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    type: 'strength',
    muscle: 'chest',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Perform dumbbell press on an inclined bench to target upper chest.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['incline_dumbbell_press']],
    gifUrl: exerciseImages['incline_dumbbell_press'],
  },
  {
    id: 'incline_dumbbell_flyes',
    name: 'Incline Dumbbell Flyes',
    type: 'strength',
    muscle: 'chest',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Perform dumbbell flyes on an inclined bench to target upper chest.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders'],
    images: [exerciseImages['incline_dumbbell_flyes']],
    gifUrl: exerciseImages['incline_dumbbell_flyes'],
  },
  {
    id: 'decline_dumbbell_press',
    name: 'Decline Dumbbell Press',
    type: 'strength',
    muscle: 'chest',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Perform dumbbell press on a decline bench to target lower chest.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['decline_dumbbell_press']],
    gifUrl: exerciseImages['decline_dumbbell_press'],
  },

  {
    id: 'cable_crossover',
    name: 'Cable Crossover',
    type: 'strength',
    muscle: 'chest',
    equipment: 'cable',
    difficulty: 'intermediate',
    instructions: 'Use cable machine to perform crossover motion targeting chest muscles.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders'],
    images: [exerciseImages['cable_crossover']],
    gifUrl: exerciseImages['cable_crossover'],
  },
  {
    id: 'dips_chest',
    name: 'Dips - Chest Version',
    type: 'strength',
    muscle: 'chest',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Perform dips with forward lean to emphasize chest muscles.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    images: [exerciseImages['dips_chest']],
    gifUrl: exerciseImages['dips_chest'],
  },
  {
    id: 'wide_grip_bench_press',
    name: 'Wide-Grip Bench Press',
    type: 'strength',
    muscle: 'chest',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Perform bench press with wider grip to emphasize outer chest.',
    bodyPart: 'chest',
    target: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    images: [exerciseImages['wide_grip_bench_press']],
    gifUrl: exerciseImages['wide_grip_bench_press'],
  },

  // BACK EXERCISES
  {
    id: 'pullups',
    name: 'Pullups',
    type: 'strength',
    muscle: 'back',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Grab the pull-up bar with palms facing forward. Pull your torso up until the bar touches your upper chest by drawing the shoulders and upper arms down and back.',
    bodyPart: 'back',
    target: 'lats',
    secondaryMuscles: ['biceps', 'middle back'],
    images: [exerciseImages['pullups']],
    gifUrl: exerciseImages['pullups'],
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    type: 'strength',
    muscle: 'back',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Similar to pull-ups but with palms facing towards you. This variation emphasizes biceps more.',
    bodyPart: 'back',
    target: 'lats',
    secondaryMuscles: ['biceps'],
    images: [exerciseImages['chin_up']],
    gifUrl: exerciseImages['chin_up'],
  },
  {
    id: 'bent_over_barbell_row',
    name: 'Bent Over Barbell Row',
    type: 'strength',
    muscle: 'back',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Bend over and row the barbell to your lower chest. Keep your back straight throughout the movement.',
    bodyPart: 'back',
    target: 'middle back',
    secondaryMuscles: ['lats', 'biceps'],
    images: [exerciseImages['bent_over_barbell_row']],
    gifUrl: exerciseImages['bent_over_barbell_row'],
  },
  {
    id: 'one_arm_dumbbell_row',
    name: 'One-Arm Dumbbell Row',
    type: 'strength',
    muscle: 'back',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Support yourself with one hand on a bench and row the dumbbell with the other arm.',
    bodyPart: 'back',
    target: 'middle back',
    secondaryMuscles: ['lats', 'biceps'],
    images: [exerciseImages['one_arm_dumbbell_row']],
    gifUrl: exerciseImages['one_arm_dumbbell_row'],
  },
  {
    id: 'wide_grip_lat_pulldown',
    name: 'Wide-Grip Lat Pulldown',
    type: 'strength',
    muscle: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Pull the bar down to your upper chest using a wide grip.',
    bodyPart: 'back',
    target: 'lats',
    secondaryMuscles: ['biceps', 'middle back'],
    images: [exerciseImages['wide_grip_lat_pulldown']],
    gifUrl: exerciseImages['wide_grip_lat_pulldown'],
  },
  {
    id: 'seated_cable_rows',
    name: 'Seated Cable Rows',
    type: 'strength',
    muscle: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Sit at a cable row station and pull the handle to your abdomen.',
    bodyPart: 'back',
    target: 'middle back',
    secondaryMuscles: ['lats', 'biceps'],
    images: [exerciseImages['seated_cable_rows']],
    gifUrl: exerciseImages['seated_cable_rows'],
  },
  {
    id: 't_bar_row',
    name: 'T-Bar Row',
    type: 'strength',
    muscle: 'back',
    equipment: 'other',
    difficulty: 'intermediate',
    instructions: 'Use T-bar to perform rowing motion targeting middle back.',
    bodyPart: 'back',
    target: 'middle back',
    secondaryMuscles: ['lats', 'biceps'],
    images: [exerciseImages['t_bar_row']],
    gifUrl: exerciseImages['t_bar_row'],
  },
  {
    id: 'reverse_flyes',
    name: 'Reverse Flyes',
    type: 'strength',
    muscle: 'back',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Bend over and perform reverse fly motion to target rear delts and upper back.',
    bodyPart: 'back',
    target: 'rear delts',
    secondaryMuscles: ['middle back'],
    images: [exerciseImages['reverse_flyes']],
    gifUrl: exerciseImages['reverse_flyes'],
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    type: 'strength',
    muscle: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Pull cable to face level targeting rear delts and upper back.',
    bodyPart: 'back',
    target: 'rear delts',
    secondaryMuscles: ['middle back'],
    images: [exerciseImages['face_pull']],
    gifUrl: exerciseImages['face_pull'],
  },
  {
    id: 'hyperextensions',
    name: 'Hyperextensions',
    type: 'strength',
    muscle: 'back',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Perform back extensions to strengthen lower back muscles.',
    bodyPart: 'back',
    target: 'lower back',
    secondaryMuscles: ['glutes'],
    images: [exerciseImages['hyperextensions']],
    gifUrl: exerciseImages['hyperextensions'],
  },

  // LEG EXERCISES
  {
    id: 'barbell_squat',
    name: 'Barbell Squat',
    type: 'strength',
    muscle: 'legs',
    equipment: 'barbell',
    difficulty: 'beginner',
    instructions: 'This exercise is best performed inside a squat rack for safety purposes. Step under the bar and place it on your shoulders. Squat down until your thighs are parallel to the floor, then stand back up.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['calves', 'glutes', 'hamstrings', 'lower back'],
    images: [exerciseImages['barbell_squat']],
    gifUrl: exerciseImages['barbell_squat'],
  },
  {
    id: 'bodyweight_squat',
    name: 'Bodyweight Squat',
    type: 'strength',
    muscle: 'legs',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Stand with feet shoulder-width apart. Lower your body as if sitting back into a chair until thighs are parallel to floor.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    images: [exerciseImages['bodyweight_squat']],
    gifUrl: exerciseImages['bodyweight_squat'],
  },
  {
    id: 'dumbbell_lunges',
    name: 'Dumbbell Lunges',
    type: 'strength',
    muscle: 'legs',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold dumbbells at your sides and step forward into a lunge position. Lower your body until both knees are at 90 degrees.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    images: [exerciseImages['dumbbell_lunges']],
    gifUrl: exerciseImages['dumbbell_lunges'],
  },
  {
    id: 'barbell_deadlift',
    name: 'Barbell Deadlift',
    type: 'strength',
    muscle: 'legs',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Stand with feet hip-width apart, bend down and grab the barbell. Lift by extending your hips and knees.',
    bodyPart: 'legs',
    target: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower back', 'traps'],
    images: [exerciseImages['barbell_deadlift']],
    gifUrl: exerciseImages['barbell_deadlift'],
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    type: 'strength',
    muscle: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit on the leg press machine and push the weight with your legs.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    images: [exerciseImages['leg_press']],
    gifUrl: exerciseImages['leg_press'],
  },
  {
    id: 'leg_extensions',
    name: 'Leg Extensions',
    type: 'strength',
    muscle: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit on the leg extension machine and extend your legs.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: [],
    images: [exerciseImages['leg_extensions']],
    gifUrl: exerciseImages['leg_extensions'],
  },
  {
    id: 'lying_leg_curls',
    name: 'Lying Leg Curls',
    type: 'strength',
    muscle: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Lie on the leg curl machine and curl your legs up.',
    bodyPart: 'legs',
    target: 'hamstrings',
    secondaryMuscles: ['calves'],
    images: [exerciseImages['lying_leg_curls']],
    gifUrl: exerciseImages['lying_leg_curls'],
  },
  {
    id: 'standing_calf_raises',
    name: 'Standing Calf Raises',
    type: 'strength',
    muscle: 'legs',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Stand on your toes and raise your heels as high as possible. Hold briefly then lower.',
    bodyPart: 'legs',
    target: 'calves',
    secondaryMuscles: [],
    images: [exerciseImages['standing_calf_raises']],
    gifUrl: exerciseImages['standing_calf_raises'],
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    type: 'strength',
    muscle: 'legs',
    equipment: 'machine',
    difficulty: 'intermediate',
    instructions: 'Use the hack squat machine to perform squats with back support.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    images: [exerciseImages['barbell_squat']], // Using barbell squat as fallback
    gifUrl: exerciseImages['barbell_squat'],
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    type: 'strength',
    muscle: 'legs',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold a dumbbell at chest level and perform squats.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    images: [exerciseImages['goblet_squat']],
    gifUrl: exerciseImages['goblet_squat'],
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    type: 'strength',
    muscle: 'legs',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Perform deadlift with straight legs to target hamstrings and glutes.',
    bodyPart: 'legs',
    target: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower back'],
    images: [exerciseImages['romanian_deadlift']],
    gifUrl: exerciseImages['romanian_deadlift'],
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    type: 'strength',
    muscle: 'legs',
    equipment: 'barbell',
    difficulty: 'advanced',
    instructions: 'Perform squats with barbell held in front position.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    images: [exerciseImages['front_squat']],
    gifUrl: exerciseImages['front_squat'],
  },
  {
    id: 'walking_lunges',
    name: 'Walking Lunges',
    type: 'strength',
    muscle: 'legs',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Perform lunges while walking forward with barbell.',
    bodyPart: 'legs',
    target: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    images: [exerciseImages['walking_lunges']],
    gifUrl: exerciseImages['walking_lunges'],
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    type: 'strength',
    muscle: 'legs',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Perform deadlift with wide stance to emphasize inner thighs.',
    bodyPart: 'legs',
    target: 'hamstrings',
    secondaryMuscles: ['glutes', 'quadriceps'],
    images: [exerciseImages['sumo_deadlift']],
    gifUrl: exerciseImages['sumo_deadlift'],
  },
  // BICEP EXERCISES
  {
    id: 'dumbbell_bicep_curl',
    name: 'Dumbbell Bicep Curl',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Stand up straight with a dumbbell in each hand at arms length. Keep your elbows close to your torso and curl the weights while contracting your biceps.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['dumbbell_bicep_curl']],
    gifUrl: exerciseImages['dumbbell_bicep_curl'],
  },
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'barbell',
    difficulty: 'beginner',
    instructions: 'Stand with feet shoulder-width apart, hold barbell with underhand grip and curl it up to your chest.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['barbell_curl']],
    gifUrl: exerciseImages['barbell_curl'],
  },
  {
    id: 'hammer_curls',
    name: 'Hammer Curls',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold dumbbells with neutral grip (palms facing each other) and curl them up.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['hammer_curls']],
    gifUrl: exerciseImages['hammer_curls'],
  },
  {
    id: 'concentration_curls',
    name: 'Concentration Curls',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Sit on a bench, rest your elbow on your thigh and curl the dumbbell up with focused concentration.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: [],
    images: [exerciseImages['concentration_curls']],
    gifUrl: exerciseImages['concentration_curls'],
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Use a preacher bench to perform curls with strict form.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['preacher_curl']],
    gifUrl: exerciseImages['preacher_curl'],
  },
  {
    id: 'ez_bar_curl',
    name: 'EZ-Bar Curl',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'barbell',
    difficulty: 'beginner',
    instructions: 'Use an EZ-bar to perform curls with a more comfortable grip.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['barbell_curl']], // Using barbell curl as fallback
    gifUrl: exerciseImages['barbell_curl'],
  },
  {
    id: 'cable_bicep_curl',
    name: 'Cable Bicep Curl',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Use a cable machine to perform bicep curls with constant tension.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['cable_bicep_curl']],
    gifUrl: exerciseImages['cable_bicep_curl'],
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Perform dumbbell curls on an inclined bench for better stretch.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['incline_dumbbell_curl']],
    gifUrl: exerciseImages['incline_dumbbell_curl'],
  },
  {
    id: 'alternate_hammer_curl',
    name: 'Alternate Hammer Curl',
    type: 'strength',
    muscle: 'biceps',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Alternate hammer curls between arms for balanced development.',
    bodyPart: 'biceps',
    target: 'biceps',
    secondaryMuscles: ['forearms'],
    images: [exerciseImages['alternate_hammer_curl']],
    gifUrl: exerciseImages['alternate_hammer_curl'],
  },

  // TRICEP EXERCISES
  {
    id: 'triceps_pushdown',
    name: 'Triceps Pushdown',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Using a cable machine, push the bar down using only your triceps. Keep your elbows at your sides.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: [],
    images: [exerciseImages['triceps_pushdown']],
    gifUrl: exerciseImages['triceps_pushdown'],
  },
  {
    id: 'dips_triceps_version',
    name: 'Dips - Triceps Version',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Using parallel bars or a dip station, lower your body by bending your elbows, then push back up.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    images: [exerciseImages['dips_triceps_version']],
    gifUrl: exerciseImages['dips_triceps_version'],
  },
  {
    id: 'tricep_dumbbell_kickback',
    name: 'Tricep Dumbbell Kickback',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Bend over, keep your upper arm parallel to the floor and extend the dumbbell back using your triceps.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: [],
    images: [exerciseImages['tricep_dumbbell_kickback']],
    gifUrl: exerciseImages['tricep_dumbbell_kickback'],
  },
  {
    id: 'bench_dips',
    name: 'Bench Dips',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Sit on the edge of a bench, place hands beside your hips, and lower your body by bending your elbows.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: ['shoulders'],
    images: [exerciseImages['bench_dips']],
    gifUrl: exerciseImages['bench_dips'],
  },
  {
    id: 'ez_bar_skullcrusher',
    name: 'EZ-Bar Skullcrusher',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Lie on a bench and lower the EZ-bar to your forehead, then extend back up.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: [],
    images: [exerciseImages['ez_bar_skullcrusher']],
    gifUrl: exerciseImages['ez_bar_skullcrusher'],
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Hold a dumbbell overhead with both hands and lower it behind your head, then extend back up.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: [],
    images: [exerciseImages['overhead_tricep_extension']],
    gifUrl: exerciseImages['overhead_tricep_extension'],
  },
  {
    id: 'close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Perform bench press with narrow grip to emphasize triceps.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: ['chest'],
    images: [exerciseImages['close_grip_bench_press']],
    gifUrl: exerciseImages['close_grip_bench_press'],
  },
  {
    id: 'tricep_rope_pushdown',
    name: 'Tricep Rope Pushdown',
    type: 'strength',
    muscle: 'triceps',
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Use rope attachment on cable machine for tricep pushdowns.',
    bodyPart: 'triceps',
    target: 'triceps',
    secondaryMuscles: [],
    images: [exerciseImages['tricep_rope_pushdown']],
    gifUrl: exerciseImages['tricep_rope_pushdown'],
  },
  // SHOULDER EXERCISES
  {
    id: 'dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'While holding a dumbbell in each hand, sit on a bench with back support. Raise the dumbbells to shoulder height and press them upward until they touch at the top.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: ['triceps'],
    images: [exerciseImages['dumbbell_shoulder_press']],
    gifUrl: exerciseImages['dumbbell_shoulder_press'],
  },
  {
    id: 'side_lateral_raise',
    name: 'Side Lateral Raise',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold dumbbells at your sides and raise them out to the sides until they reach shoulder height.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: [],
    images: [exerciseImages['side_lateral_raise']],
    gifUrl: exerciseImages['side_lateral_raise'],
  },
  {
    id: 'front_dumbbell_raise',
    name: 'Front Dumbbell Raise',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold dumbbells in front of your thighs and raise them forward until they reach shoulder height.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: [],
    images: [exerciseImages['front_dumbbell_raise']],
    gifUrl: exerciseImages['front_dumbbell_raise'],
  },
  {
    id: 'barbell_shoulder_press',
    name: 'Barbell Shoulder Press',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Stand with feet shoulder-width apart and press the barbell overhead from shoulder height.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: ['triceps'],
    images: [exerciseImages['barbell_shoulder_press']],
    gifUrl: exerciseImages['barbell_shoulder_press'],
  },
  {
    id: 'arnold_dumbbell_press',
    name: 'Arnold Dumbbell Press',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Start with palms facing you, rotate and press the dumbbells overhead.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: ['triceps'],
    images: [exerciseImages['arnold_dumbbell_press']],
    gifUrl: exerciseImages['arnold_dumbbell_press'],
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Bend over and raise dumbbells out to the sides to target rear deltoids.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: ['back'],
    images: [exerciseImages['rear_delt_fly']],
    gifUrl: exerciseImages['rear_delt_fly'],
  },
  {
    id: 'upright_row',
    name: 'Upright Row',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Pull the barbell up to your chin with elbows leading the movement.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: ['traps'],
    images: [exerciseImages['upright_row']],
    gifUrl: exerciseImages['upright_row'],
  },
  {
    id: 'military_press',
    name: 'Military Press',
    type: 'strength',
    muscle: 'shoulders',
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Stand at attention and press barbell overhead with strict form.',
    bodyPart: 'shoulders',
    target: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    images: [exerciseImages['military_press']],
    gifUrl: exerciseImages['military_press'],
  },

  // CORE EXERCISES
  {
    id: 'crunches',
    name: 'Crunches',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Lie flat on your back with your feet flat on the ground. Place your hands lightly on either side of your head and roll your shoulders off the floor while contracting your abdominals.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: [],
    images: [exerciseImages['crunches']],
    gifUrl: exerciseImages['crunches'],
  },
  {
    id: 'plank',
    name: 'Plank',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Start in a push-up position but rest on your forearms. Keep your body in a straight line from head to heels.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: ['shoulders', 'back'],
    images: [exerciseImages['plank']],
    gifUrl: exerciseImages['plank'],
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Sit on the floor with knees bent, lean back slightly and twist your torso from side to side.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: ['obliques'],
    images: [exerciseImages['russian_twist']],
    gifUrl: exerciseImages['russian_twist'],
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'advanced',
    instructions: 'Hang from a pull-up bar and raise your legs up to your chest, then lower them back down.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: [],
    images: [exerciseImages['hanging_leg_raise']],
    gifUrl: exerciseImages['hanging_leg_raise'],
  },
  {
    id: 'sit_up',
    name: 'Sit-Up',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Lie on your back with knees bent and sit up to bring your chest to your knees.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: [],
    images: [exerciseImages['sit_up']],
    gifUrl: exerciseImages['sit_up'],
  },
  {
    id: 'bicycle_crunches',
    name: 'Bicycle Crunches',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Lie on your back and alternate bringing opposite elbow to knee in a cycling motion.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: ['obliques'],
    images: [exerciseImages['bicycle_crunches']],
    gifUrl: exerciseImages['bicycle_crunches'],
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Lie on your back and alternate extending opposite arm and leg while keeping core stable.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: [],
    images: [exerciseImages['crunches']], // Using crunches as fallback
    gifUrl: exerciseImages['crunches'],
  },
  {
    id: 'leg_raises',
    name: 'Leg Raises',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Lie on your back and raise your legs up to 90 degrees, then lower them back down.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: [],
    images: [exerciseImages['leg_raises']],
    gifUrl: exerciseImages['leg_raises'],
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    type: 'strength',
    muscle: 'core',
    equipment: 'other',
    difficulty: 'advanced',
    instructions: 'Use ab wheel to roll out and back while maintaining core tension.',
    bodyPart: 'core',
    target: 'abdominals',
    secondaryMuscles: ['shoulders'],
    images: [exerciseImages['ab_wheel_rollout']],
    gifUrl: exerciseImages['ab_wheel_rollout'],
  },
  {
    id: 'oblique_crunches',
    name: 'Oblique Crunches',
    type: 'strength',
    muscle: 'core',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Perform crunches targeting the oblique muscles on the sides.',
    bodyPart: 'core',
    target: 'obliques',
    secondaryMuscles: ['abdominals'],
    images: [exerciseImages['oblique_crunches']],
    gifUrl: exerciseImages['oblique_crunches'],
  },

  // CARDIO EXERCISES
  {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    type: 'cardio',
    muscle: 'cardio',
    equipment: 'body only',
    difficulty: 'intermediate',
    instructions: 'Start in a plank position and alternate bringing knees to chest in a running motion.',
    bodyPart: 'cardio',
    target: 'cardiovascular system',
    secondaryMuscles: ['core', 'shoulders'],
    images: [exerciseImages['mountain_climbers']],
    gifUrl: exerciseImages['mountain_climbers'],
  },
  {
    id: 'rope_jumping',
    name: 'Rope Jumping',
    type: 'cardio',
    muscle: 'cardio',
    equipment: 'other',
    difficulty: 'beginner',
    instructions: 'Jump rope continuously for the desired duration.',
    bodyPart: 'cardio',
    target: 'cardiovascular system',
    secondaryMuscles: ['calves', 'shoulders'],
    images: [exerciseImages['rope_jumping']],
    gifUrl: exerciseImages['rope_jumping'],
  },
  {
    id: 'running_treadmill',
    name: 'Running (Treadmill)',
    type: 'cardio',
    muscle: 'cardio',
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Run on a treadmill at your desired pace and duration.',
    bodyPart: 'cardio',
    target: 'cardiovascular system',
    secondaryMuscles: ['legs'],
    images: [exerciseImages['running_treadmill']],
    gifUrl: exerciseImages['running_treadmill'],
  },
  {
    id: 'burpees',
    name: 'Burpees',
    type: 'cardio',
    muscle: 'cardio',
    equipment: 'body only',
    difficulty: 'advanced',
    instructions: 'Squat down, jump back to plank, do a push-up, jump feet back to squat, then jump up.',
    bodyPart: 'cardio',
    target: 'cardiovascular system',
    secondaryMuscles: ['chest', 'legs', 'core'],
    images: [exerciseImages['burpees']],
    gifUrl: exerciseImages['burpees'],
  },
  {
    id: 'jumping_jacks',
    name: 'Jumping Jacks',
    type: 'cardio',
    muscle: 'cardio',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Jump while spreading legs and raising arms overhead, then return to start.',
    bodyPart: 'cardio',
    target: 'cardiovascular system',
    secondaryMuscles: ['legs', 'shoulders'],
    images: [exerciseImages['jumping_jacks']],
    gifUrl: exerciseImages['jumping_jacks'],
  },
  {
    id: 'high_knees',
    name: 'High Knees',
    type: 'cardio',
    muscle: 'cardio',
    equipment: 'body only',
    difficulty: 'beginner',
    instructions: 'Run in place while bringing knees up to waist level.',
    bodyPart: 'cardio',
    target: 'cardiovascular system',
    secondaryMuscles: ['legs', 'core'],
    images: [exerciseImages['high_knees']],
    gifUrl: exerciseImages['high_knees'],
  },
  {
    id: 'box_jumps',
    name: 'Box Jumps',
    type: 'cardio',
    muscle: 'cardio',
    equipment: 'other',
    difficulty: 'intermediate',
    instructions: 'Jump onto a box or platform, then step or jump back down.',
    bodyPart: 'cardio',
    target: 'cardiovascular system',
    secondaryMuscles: ['legs'],
    images: [exerciseImages['box_jumps']],
    gifUrl: exerciseImages['box_jumps'],
  },
];

// Helper function to categorize exercises by muscle group
const categorizeExercise = (exercise: Exercise): string => {
  const primaryMuscle = exercise.muscle.toLowerCase();
  
  // Direct mapping
  if (muscleMapping[primaryMuscle]) {
    return muscleMapping[primaryMuscle];
  }
  
  // Check target muscle
  const target = exercise.target?.toLowerCase() || '';
  if (muscleMapping[target]) {
    return muscleMapping[target];
  }
  
  // Check body part
  const bodyPart = exercise.bodyPart?.toLowerCase() || '';
  if (muscleMapping[bodyPart]) {
    return muscleMapping[bodyPart];
  }
  
  // Fallback categorization based on exercise name
  const name = exercise.name.toLowerCase();
  if (name.includes('push') || name.includes('bench') || name.includes('chest') || name.includes('fly')) {
    return 'chest';
  }
  if (name.includes('pull') || name.includes('row') || name.includes('lat') || name.includes('back')) {
    return 'back';
  }
  if (name.includes('squat') || name.includes('lunge') || name.includes('leg') || name.includes('calf')) {
    return 'legs';
  }
  if (name.includes('curl') && !name.includes('leg')) {
    return 'biceps';
  }
  if (name.includes('tricep') || name.includes('dip') || name.includes('extension')) {
    return 'triceps';
  }
  if (name.includes('shoulder') || name.includes('press') || name.includes('raise')) {
    return 'shoulders';
  }
  if (name.includes('crunch') || name.includes('plank') || name.includes('abs') || name.includes('core')) {
    return 'core';
  }
  if (name.includes('run') || name.includes('jump') || name.includes('cardio') || name.includes('mountain')) {
    return 'cardio';
  }
  
  return 'chest'; // Default fallback
};

// Service functions
export const exerciseService = {
  // Get all exercises
  getAllExercises: async (): Promise<Exercise[]> => {
    try {
      return ALL_EXERCISES;
    } catch (error) {
      console.error('Error fetching exercises:', error);
      throw error;
    }
  },

  // Get exercises by body part/muscle group
  getExercisesByBodyPart: async (bodyPart: string): Promise<Exercise[]> => {
    try {
      const filtered = ALL_EXERCISES.filter(exercise => {
        const category = categorizeExercise(exercise);
        return category === bodyPart.toLowerCase();
      });
      
      console.log(`Found ${filtered.length} exercises for ${bodyPart}`);
      return filtered;
    } catch (error) {
      console.error('Error fetching exercises by body part:', error);
      throw error;
    }
  },

  // Get exercise by ID
  getExerciseById: async (id: string): Promise<Exercise | null> => {
    try {
      const exercise = ALL_EXERCISES.find(ex => ex.id === id);
      return exercise || null;
    } catch (error) {
      console.error('Error fetching exercise by ID:', error);
      throw error;
    }
  },

  // Search exercises
  searchExercises: async (query: string): Promise<Exercise[]> => {
    try {
      const searchTerm = query.toLowerCase();
      return ALL_EXERCISES.filter(exercise =>
        exercise.name.toLowerCase().includes(searchTerm) ||
        exercise.muscle.toLowerCase().includes(searchTerm) ||
        exercise.equipment.toLowerCase().includes(searchTerm) ||
        exercise.target?.toLowerCase().includes(searchTerm)
      );
    } catch (error) {
      console.error('Error searching exercises:', error);
      throw error;
    }
  },

  // Get exercises by equipment
  getExercisesByEquipment: async (equipment: string): Promise<Exercise[]> => {
    try {
      return ALL_EXERCISES.filter(exercise =>
        exercise.equipment.toLowerCase().includes(equipment.toLowerCase())
      );
    } catch (error) {
      console.error('Error fetching exercises by equipment:', error);
      throw error;
    }
  },

  // Get exercises by difficulty
  getExercisesByDifficulty: async (difficulty: string): Promise<Exercise[]> => {
    try {
      return ALL_EXERCISES.filter(exercise =>
        exercise.difficulty?.toLowerCase() === difficulty.toLowerCase()
      );
    } catch (error) {
      console.error('Error fetching exercises by difficulty:', error);
      throw error;
    }
  },
};